language: perl
perl:
  - "5.20"
  - "5.22"
  - "5.24"
before_install:
  - "git clone https://github.com/sniperovitch/cocktail.git"
  - "cpanm Dancer2"
cache:
  directories:
  - $HOME/perl5
notifications:
  irc: "chat.freenode.net#pressecitron"
